import { FastifyPluginAsync } from 'fastify'

const ENDPOINTS = [
  {
    grupo: 'Jogos',
    icone: '📅',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/jogos/hoje',
        descricao: 'Jogos de times brasileiros hoje (Sofascore → ESPN fallback)',
        params: [],
        exemplo: '/api/jogos/hoje',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/jogos',
        descricao: 'Jogos por data específica',
        params: [{ nome: 'data', tipo: 'query', formato: 'YYYY-MM-DD', obrigatorio: false, descricao: 'Data desejada. Padrão: hoje' }],
        exemplo: '/api/jogos?data=2026-05-01',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Times',
    icone: '🏟️',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/times',
        descricao: 'Lista todos os times brasileiros com dados estáticos (escudo, estádio, história, títulos)',
        params: [],
        exemplo: '/api/times',
        resposta: '{ success, data: TimeSeed[], total, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/times/:slug',
        descricao: 'Detalhes completos de um time: info, elenco (ESPN), próximos jogos, últimos jogos',
        params: [{ nome: 'slug', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Ex: flamengo, palmeiras, atletico-mg' }],
        exemplo: '/api/times/flamengo',
        resposta: '{ success, data: { ...time, elenco, jogosHoje, proximosJogos, ultimosJogos }, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/times/:slug/elenco',
        descricao: 'Elenco atual do time via ESPN',
        params: [{ nome: 'slug', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug do time' }],
        exemplo: '/api/times/flamengo/elenco',
        resposta: '{ success, data: JogadorElenco[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/times/:slug/jogos',
        descricao: 'Jogos de hoje filtrados pelo time',
        params: [{ nome: 'slug', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug do time' }],
        exemplo: '/api/times/palmeiras/jogos',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Campeonatos',
    icone: '🏆',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/campeonatos',
        descricao: 'Lista todos os campeonatos disponíveis',
        params: [],
        exemplo: '/api/campeonatos',
        resposta: '{ success, data: Campeonato[], timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/campeonatos/:slug/tabela',
        descricao: 'Tabela de classificação via ESPN. Slugs disponíveis: brasileirao-serie-a, brasileirao-serie-b, libertadores, sul-americana, copa-do-brasil',
        params: [{ nome: 'slug', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug do campeonato' }],
        exemplo: '/api/campeonatos/brasileirao-serie-a/tabela',
        resposta: '{ success, data: PosicaoTabela[], cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/campeonatos/:slug/artilharia',
        descricao: 'Artilharia do campeonato via ESPN. Disponível apenas para brasileirao-serie-a',
        params: [{ nome: 'slug', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug do campeonato' }],
        exemplo: '/api/campeonatos/brasileirao-serie-a/artilharia',
        resposta: '{ success, data: Artilheiro[], cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/campeonatos/brasileirao/proximos',
        descricao: 'Próximos jogos do Brasileirão nos próximos 14 dias',
        params: [],
        exemplo: '/api/campeonatos/brasileirao/proximos',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Transmissões',
    icone: '📡',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/transmissoes/hoje',
        descricao: 'Canais de transmissão dos jogos de hoje (extraídos junto com os jogos)',
        params: [],
        exemplo: '/api/transmissoes/hoje',
        resposta: '{ success, data: { jogo, campeonato, horario, transmissoes: Transmissao[] }[], timestamp }',
      },
    ],
  },
  {
    grupo: 'Conteúdo',
    icone: '📢',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/conteudos/sugestoes',
        descricao: 'Sugestões de posts para redes sociais com base nos jogos do dia',
        params: [],
        exemplo: '/api/conteudos/sugestoes',
        resposta: '{ success, data: SugestaoConteudo[], total, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/noticias',
        descricao: 'Manchetes de esporte coletadas de MSN, Terra, UOL e Lance',
        params: [{ nome: 'limit', tipo: 'query', formato: 'number (1-60)', obrigatorio: false, descricao: 'Quantidade máxima de notícias' }],
        exemplo: '/api/noticias?limit=12',
        resposta: '{ success, data: NoticiaEsporte[], total, fontes, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/conteudos/noticias',
        descricao: 'Alias de conteúdo para as manchetes esportivas das fontes externas',
        params: [],
        exemplo: '/api/conteudos/noticias',
        resposta: '{ success, data: NoticiaEsporte[], total, timestamp }',
      },
    ],
  },
  {
    grupo: 'Busca',
    icone: '🔍',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/busca',
        descricao: 'Busca global por times, campeonatos e jogos do dia',
        params: [{ nome: 'q', tipo: 'query', formato: 'string (min 2, max 100 chars)', obrigatorio: true, descricao: 'Termo de busca' }],
        exemplo: '/api/busca?q=flamengo',
        resposta: '{ success, data: { times, campeonatos, jogos }, timestamp }',
      },
    ],
  },
  {
    grupo: 'Agenda Unificada',
    icone: '🗓️',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/agenda',
        descricao: 'Agenda unificada do dia: futebol BR + futebol internacional + NBA + UFC, ordenada por horário',
        params: [
          { nome: 'data', tipo: 'query', formato: 'YYYY-MM-DD', obrigatorio: false, descricao: 'Data desejada. Padrão: hoje' },
          { nome: 'esporte', tipo: 'query', formato: 'futebol | basquete | mma', obrigatorio: false, descricao: 'Filtra por esporte' },
        ],
        exemplo: '/api/agenda?data=2026-06-15&esporte=futebol',
        resposta: '{ success, data: AgendaItem[], total, esportes:{futebol,basquete,mma}, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/agenda/semana',
        descricao: 'Agenda dos próximos 7 dias agrupada por data',
        params: [],
        exemplo: '/api/agenda/semana',
        resposta: '{ success, data: { [data]: AgendaItem[] }, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'NBA / Basquete',
    icone: '🏀',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/nba/jogos/hoje',
        descricao: 'Jogos da NBA hoje (ESPN scoreboard) com placares ao vivo, quartos, destaques e transmissões',
        params: [],
        exemplo: '/api/nba/jogos/hoje',
        resposta: '{ success, data: JogoNBA[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/nba/jogos',
        descricao: 'Jogos da NBA por data',
        params: [{ nome: 'data', tipo: 'query', formato: 'YYYY-MM-DD', obrigatorio: false, descricao: 'Data desejada. Padrão: hoje' }],
        exemplo: '/api/nba/jogos?data=2026-06-05',
        resposta: '{ success, data: JogoNBA[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/nba/proximos',
        descricao: 'Próximos 7 dias de jogos da NBA',
        params: [],
        exemplo: '/api/nba/proximos',
        resposta: '{ success, data: JogoNBA[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/nba/tabela',
        descricao: 'Classificação NBA — Conferência Leste e Oeste',
        params: [],
        exemplo: '/api/nba/tabela',
        resposta: '{ success, data: { leste: PosicaoTabela[], oeste: PosicaoTabela[] }, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'UFC / Lutas',
    icone: '🥊',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/ufc/proximo',
        descricao: 'Próximo evento UFC com card completo (lutadores, categorias, cartel, transmissões)',
        params: [],
        exemplo: '/api/ufc/proximo',
        resposta: '{ success, data: EventoUFC, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/ufc/calendario',
        descricao: 'Calendário completo de eventos UFC futuros (UFC Numbered + Fight Nights)',
        params: [],
        exemplo: '/api/ufc/calendario',
        resposta: '{ success, data: EventoUFC[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/ufc/eventos/:id',
        descricao: 'Detalha um evento UFC específico com todas as lutas do card',
        params: [{ nome: 'id', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'ID do evento na ESPN' }],
        exemplo: '/api/ufc/eventos/600058948',
        resposta: '{ success, data: EventoUFC, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Futebol Internacional',
    icone: '🌎',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/futebol-internacional/ligas',
        descricao: 'Lista todas as ligas internacionais suportadas (Champions, Premier, La Liga, Serie A, Bundesliga, Ligue 1, Europa, Conference, Copa do Mundo, Eliminatórias)',
        params: [],
        exemplo: '/api/futebol-internacional/ligas',
        resposta: '{ success, data: LigaInternacional[], total, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/futebol-internacional/:liga/jogos',
        descricao: 'Jogos da liga em uma data. Slugs: champions-league, europa-league, conference-league, premier-league, la-liga, serie-a-italia, bundesliga, ligue-1',
        params: [
          { nome: 'liga', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug da liga' },
          { nome: 'data', tipo: 'query', formato: 'YYYY-MM-DD', obrigatorio: false, descricao: 'Data desejada. Padrão: hoje' },
        ],
        exemplo: '/api/futebol-internacional/champions-league/jogos',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/futebol-internacional/:liga/proximos',
        descricao: 'Próximos 14 dias de jogos da liga',
        params: [{ nome: 'liga', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug da liga' }],
        exemplo: '/api/futebol-internacional/premier-league/proximos',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/futebol-internacional/:liga/tabela',
        descricao: 'Tabela de classificação da liga',
        params: [{ nome: 'liga', tipo: 'path', formato: 'string', obrigatorio: true, descricao: 'Slug da liga' }],
        exemplo: '/api/futebol-internacional/la-liga/tabela',
        resposta: '{ success, data: PosicaoTabela[], cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Copa do Mundo 2026',
    icone: '🌍',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/copa-mundo',
        descricao: 'Informações gerais da Copa do Mundo FIFA 2026 (sedes, datas, mascote, bola)',
        params: [],
        exemplo: '/api/copa-mundo',
        resposta: '{ success, data: InfoCopaMundo2026, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/copa-mundo/sedes',
        descricao: '16 cidades-sede com estádios e capacidade',
        params: [],
        exemplo: '/api/copa-mundo/sedes',
        resposta: '{ success, data: SedeCopaMundo[], total, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/copa-mundo/selecoes',
        descricao: 'Seleções classificadas (com pote, confederação e ranking FIFA)',
        params: [],
        exemplo: '/api/copa-mundo/selecoes',
        resposta: '{ success, data: SelecaoCopa[], total, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/copa-mundo/jogos',
        descricao: 'Jogos da Copa do Mundo em uma data específica',
        params: [{ nome: 'data', tipo: 'query', formato: 'YYYY-MM-DD', obrigatorio: false, descricao: 'Data desejada. Padrão: hoje' }],
        exemplo: '/api/copa-mundo/jogos?data=2026-06-11',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/copa-mundo/calendario',
        descricao: 'Calendário completo dos 104 jogos da Copa (próximos 60 dias)',
        params: [],
        exemplo: '/api/copa-mundo/calendario',
        resposta: '{ success, data: Jogo[], total, cache, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/copa-mundo/eliminatorias',
        descricao: 'Jogos das eliminatórias UEFA e CONMEBOL',
        params: [],
        exemplo: '/api/copa-mundo/eliminatorias',
        resposta: '{ success, data: { uefa: Jogo[], conmebol: Jogo[] }, cache, timestamp }',
      },
    ],
  },
  {
    grupo: 'Sistema',
    icone: '⚙️',
    rotas: [
      {
        metodo: 'GET',
        path: '/api/health',
        descricao: 'Status da API, uptime e chaves em cache',
        params: [],
        exemplo: '/api/health',
        resposta: '{ success, status, versao, uptime, cache: { total, chaves[] }, timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/docs',
        descricao: 'Esta documentação em formato JSON',
        params: [],
        exemplo: '/api/docs',
        resposta: '{ success, data: Endpoint[], timestamp }',
      },
      {
        metodo: 'GET',
        path: '/api/health/cache/clear',
        descricao: 'Limpa manualmente todo o cache em memória e persistido',
        params: [],
        exemplo: '/api/health/cache/clear',
        resposta: '{ success, cleared, message, timestamp }',
      },
    ],
  },
]

export const docsRoutes: FastifyPluginAsync = async (app) => {
  app.get('/docs', async (_req, reply) => {
    return reply.send({
      success: true,
      data: ENDPOINTS,
      timestamp: new Date().toISOString(),
    })
  })
}
